function models() {
    var models = [
        {name: "Chrysler PT Criuser", ucc: "002"},
        {name: "Chrysler 200", ucc: "006"},
        {name: "Chrysler 300", ucc: "016"},
        {name: "Chrysler 300C", ucc: "017"},
        {name: "Chrysler Sebring", ucc: "026"},
        {name: "Chrysler Town & Country", ucc: "506"},
        {name: "Dodge Dart", ucc: "006"},
        {name: "Dodge Caliber", ucc: "016"},
        {name: "Dodge Challenger", ucc: "026"},
        {name: "Dodge Avenger", ucc: "036"},
        {name: "Dodge Charger", ucc: "046"},
        {name: "Dodge Viper", ucc: "056"},
        {name: "Dodge Nitro", ucc: "206"},
        {name: "Dodge Journey", ucc: "216"},
        {name: "Dodge Durango", ucc: "226"},
        {name: "Dodge Grand Caravan", ucc: "506"},
        {name: "Ram Dakota", ucc: "406"},
        {name: "Ram 1500", ucc: "411"},
        {name: "Ram 2500/3500", ucc: "416"},
        {name: "Ram 3500 Cab Chassis", ucc: "417"},
        {name: "Ram 4500 Cab Chassis", ucc: "418"},
        {name: "Ram 5500 Cab Chassis", ucc: "419"},
        {name: "Ram Medium/Heavy Duty Cab Chassis", ucc: "421"},
        {name: "Ram Promaster 1500", ucc: "506"},
        {name: "Ram Promaster 2500", ucc: "516"},
        {name: "Ram Promaster 3500", ucc: "526"},
        {name: "Ram Promaster Window Van", ucc: "536"},
        {name: "Ram Cargo Van", ucc: "550"},
        {name: "Jeep Wrangler 2D", ucc: "206"},
        {name: "Jeep Wrangler Unlimited 4D", ucc: "211"},
        {name: "Jeep Compass", ucc: "221"},
        {name: "Jeep Patriot", ucc: "231"},
        {name: "Jeep Liberty", ucc: "241"},
        {name: "Jeep Cherokee", ucc: "251"},
        {name: "Jeep Grand Cherokee", ucc: "261"},
        {name: "Fiat 500", ucc: "006"},
        {name: "Fiat 500L", ucc: "016"},
        {name: "Ford C-Max Energi", ucc: "006"},
        {name: "Ford C-Max Hybrid", ucc: "007"},
        {name: "Ford Fiesta", ucc: "016"},
        {name: "Ford Focus", ucc: "026"},
        {name: "Ford Focus Electric", ucc: "027"},
        {name: "Ford Mustang", ucc: "036"},
        {name: "Ford Shelby GT500", ucc: "041"},
        {name: "Ford Fusion", ucc: "046"},
        {name: "Ford Fusion Hybrid", ucc: "047"},
        {name: "Ford Fusion Energi Plug-In Hybrid", ucc: "048"},
        {name: "Ford Taurus", ucc: "056"},
        {name: "Ford Escape", ucc: "206"},
        {name: "Ford Escape Hybrid", ucc: "207"},
        {name: "Ford Edge", ucc: "216"},
        {name: "Ford Explorer", ucc: "226"},
        {name: "Ford Flex", ucc: "236"},
        {name: "Ford Expedition", ucc: "246"},
        {name: "Ford Expedition EL", ucc: "256"},
        {name: "Ford Ranger", ucc: "406"},
        {name: "Ford F-150", ucc: "416"},
        {name: "Ford F-250/350 SD", ucc: "426"},
        {name: "Ford Transit Connect Passenger Wagon", ucc: "506"},
        {name: "Ford Transit Connect Cargo Van", ucc: "507"},
        {name: "Ford E-Series Passenger Wagon", ucc: "516"},
        {name: "Ford E-Series Cargo Van", ucc: "517"},
        {name: "Ford Transit-150", ucc: "520"},
        {name: "Ford Transit-250", ucc: "521"},
        {name: "Ford Transit-350", ucc: "522"},
        {name: "Lincoln MKS", ucc: "006"},
        {name: "Lincoln MKZ", ucc: "016"},
        {name: "Lincoln MKZ Hybrid", ucc: "017"},
        {name: "Lincoln MKX", ucc: "206"},
        {name: "Lincoln MKC", ucc: "207"},
        {name: "Lincoln MKT", ucc: "216"},
        {name: "Lincoln Navigator", ucc: "226"},
        {name: "Lincoln Navigator L", ucc: "236"},
        {name: "Chevrolet Spark", ucc: "006"},
        {name: "Chevrolet Spark EV", ucc: "007"},
        {name: "Chevrolet Sonic", ucc: "016"},
        {name: "Chevrolet Cruze", ucc: "026"},
        {name: "Chevrolet Volt", ucc: "036"},
        {name: "Chevrolet Camaro", ucc: "046"},
        {name: "Chevrolet Corvette", ucc: "056"},
        {name: "Chevrolet Malibu", ucc: "066"},
        {name: "Chevrolet Impala", ucc: "076"},
        {name: "Chevrolet SS", ucc: "077"},
        {name: "Chevrolet HHR", ucc: "085"},
        {name: "Chevrolet Aveo", ucc: "086"},
        {name: "Chevrolet Trax", ucc: "203"},
        {name: "Chevrolet Equinox", ucc: "206"},
        {name: "Chevrolet Traverse", ucc: "216"},
        {name: "Chevrolet Tahoe", ucc: "226"},
        {name: "Chevrolet Tahoe Hybrid", ucc: "227"},
        {name: "Chevrolet Suburban", ucc: "236"},
        {name: "Chevrolet Avalanche", ucc: "246"},
        {name: "Chevrolet Colorado", ucc: "406"},
        {name: "Chevrolet Silverado 1500", ucc: "416"},
        {name: "Chevrolet Silverado 1500 Hybrid", ucc: "417"},
        {name: "Chevrolet Silverado 2500HD/3500", ucc: "426"},
        {name: "Chevrolet Express Passenger Wagon", ucc: "506"},
        {name: "Chevrolet Express Cargo Van", ucc: "507"},
        {name: "Buick Lucerne", ucc: "005"},
        {name: "Buick Regal", ucc: "006"},
        {name: "Buick Verano", ucc: "016"},
        {name: "Buick Lacrosse", ucc: "026"},
        {name: "Buick Encore", ucc: "206"},
        {name: "Buick Enclave", ucc: "216"},
        {name: "Cadillac ATS", ucc: "006"},
        {name: "Cadillac CTS", ucc: "016"},
        {name: "Cadillac CTS-V", ucc: "017"},
        {name: "Cadillac ELR", ucc: "020"},
        {name: "Cadillac XTS", ucc: "026"},
        {name: "Cadillac DTS", ucc: "036"},
        {name: "Cadillac STS", ucc: "046"},
        {name: "Cadillac SRX", ucc: "206"},
        {name: "Cadillac Escalade", ucc: "216"},
        {name: "Cadillac Escalade Hybrid", ucc: "217"},
        {name: "Cadillac Escalade ESV", ucc: "221"},
        {name: "Cadillac Escalade EXT", ucc: "226"},
        {name: "GMC Terrain", ucc: "206"},
        {name: "GMC Terrain Denali", ucc: "207"},
        {name: "GMC Acadia", ucc: "216"},
        {name: "GMC Yukon", ucc: "226"},
        {name: "GMC Yukon Denali", ucc: "227"},
        {name: "GMC Yukon XL", ucc: "236"},
        {name: "GMC Yukon XL Denali", ucc: "237"},
        {name: "GMC Canyon", ucc: "406"},
        {name: "GMC Sierra 1500", ucc: "416"},
        {name: "GMC Sierra 2500 HD/3500", ucc: "426"},
        {name: "GMC Savana Passenger Wagon", ucc: "506"},
        {name: "GMC Savana Cargo Van", ucc: "507"},
        {name: "Tesla Model S", ucc: "006"},
        {name: "MINI Cooper Hardtop", ucc: "006"},
        {name: "MINI Cooper Coupe", ucc: "016"},
        {name: "MINI Cooper Convertible", ucc: "026"},
        {name: "MINI Cooper Roadster", ucc: "036"},
        {name: "MINI Cooper Clubman", ucc: "046"},
        {name: "MINI Cooper Countryman", ucc: "056"},
        {name: "MINI Cooper Paceman", ucc: "066"},
        {name: "BMW ActiveE", ucc: "003"},
        {name: "BMW Z4", ucc: "006"},
        {name: "BMW 1 Series", ucc: "016"},
        {name: "BMW i3", ucc: "026"},
        {name: "BMW 3 Series", ucc: "036"},
        {name: "BMW Activehybrid 3", ucc: "037"},
        {name: "BMW 2 Series", ucc: "040"},
        {name: "BMW 4 Series", ucc: "046"},
        {name: "BMW 5 Series", ucc: "056"},
        {name: "BMW Activehybrid 5", ucc: "057"},
        {name: "BMW 6 Series", ucc: "066"},
        {name: "BMW 7 Series", ucc: "076"},
        {name: "BMW 7 Series Activehybrid", ucc: "077"},
        {name: "BMW Alpina B7", ucc: "086"},
        {name: "BMW i8", ucc: "090"},
        {name: "BMW X1", ucc: "211"},
        {name: "BMW X3", ucc: "231"},
        {name: "BMW X4", ucc: "241"},
        {name: "BMW X5", ucc: "251"},
        {name: "BMW X6", ucc: "261"},
        {name: "BMW X6 ActiveHybrid", ucc: "262"},
        {name: "Mercedes CLA-Class", ucc: "001"},
        {name: "Mercedes B-Class", ucc: "002"},
        {name: "Mercedes C-Class", ucc: "006"},
        {name: "Mercedes CL-Class", ucc: "011"},
        {name: "Mercedes CLS-Class", ucc: "016"},
        {name: "Mercedes E-Class", ucc: "021"},
        {name: "Mercedes E-Class Hybrid", ucc: "022"},
        {name: "Mercedes S-Class", ucc: "031"},
        {name: "Mercedes S-Class Hybrid", ucc: "032"},
        {name: "Mercedes SLK-Class", ucc: "036"},
        {name: "Mercedes SL-Class", ucc: "041"},
        {name: "Mercedes SLS AMG", ucc: "046"},
        {name: "Mercedes GLK-Class", ucc: "206"},
        {name: "Mercedes R-Class", ucc: "216"},
        {name: "Mercedes ML-Class", ucc: "226"},
        {name: "Mercedes ML-Class Hybrid", ucc: "227"},
        {name: "Mercedes GLA-Class", ucc: "228"},
        {name: "Mercedes GL-Class", ucc: "236"},
        {name: "Mercedes G-Class", ucc: "246"},
        {name: "Smart fortwo", ucc: "006"},
        {name: "Jaguar F-Type", ucc: "006"},
        {name: "Jaguar XK", ucc: "016"},
        {name: "Jaguar XF", ucc: "026"},
        {name: "Jaguar XJ", ucc: "036"},
        {name: "Jaguar XJL", ucc: "046"},
        {name: "Land Rover LR2", ucc: "206"},
        {name: "Land Rover LR4", ucc: "216"},
        {name: "Land Rover Range Rover Evoque", ucc: "226"},
        {name: "Land Rover Range Rover Sport", ucc: "236"},
        {name: "Land Rover Range Rover", ucc: "246"},
        {name: "Porsche Boxster", ucc: "006"},
        {name: "Porsche 911", ucc: "016"},
        {name: "Porsche Cayman", ucc: "026"},
        {name: "Porsche Panamera", ucc: "036"},
        {name: "Porsche Panamera Hybrid", ucc: "037"},
        {name: "Porsche Cayenne", ucc: "216"},
        {name: "Porsche Cayenne Hybrid", ucc: "217"},
        {name: "Porsche Macan", ucc: "230"},
        {name: "Volkswagen Beetle", ucc: "006"},
        {name: "Volkswagen Eos", ucc: "016"},
        {name: "Volkswagen Golf", ucc: "026"},
        {name: "Volkswagen GTI", ucc: "036"},
        {name: "Volkswagen Jetta", ucc: "046"},
        {name: "Volkswagen Jetta Hybrid", ucc: "047"},
        {name: "Volkswagen CC", ucc: "056"},
        {name: "Volkswagen Passat", ucc: "066"},
        {name: "Volkswagen Tiguan", ucc: "206"},
        {name: "Volkswagen Touareg", ucc: "216"},
        {name: "Volkswagen Touareg Hybrid", ucc: "217"},
        {name: "Volkswagen Routan", ucc: "506"},
        {name: "Audi TT", ucc: "006"},
        {name: "Audi R8", ucc: "016"},
        {name: "Audi A3", ucc: "035"},
        {name: "Audi S3", ucc: "036"},
        {name: "Audi A4", ucc: "045"},
        {name: "Audi S4", ucc: "046"},
        {name: "Audi Allroad", ucc: "049"},
        {name: "Audi A5", ucc: "055"},
        {name: "Audi S5", ucc: "056"},
        {name: "Audi RS 5", ucc: "059"},
        {name: "Audi A6", ucc: "065"},
        {name: "Audi S6", ucc: "066"},
        {name: "Audi A7", ucc: "075"},
        {name: "Audi S7", ucc: "076"},
        {name: "Audi RS 7", ucc: "077"},
        {name: "Audi A8", ucc: "085"},
        {name: "Audi A8L", ucc: "086"},
        {name: "Audi S8", ucc: "087"},
        {name: "Audi Q3", ucc: "201"},
        {name: "Audi Q5", ucc: "205"},
        {name: "Audi Q5 Hybrid", ucc: "206"},
        {name: "Audi Q7", ucc: "216"},
        {name: "Volvo C30", ucc: "036"},
        {name: "Volvo S40", ucc: "046"},
        {name: "Volvo V50", ucc: "056"},
        {name: "Volvo S60", ucc: "066"},
        {name: "Volvo V60", ucc: "067"},
        {name: "Volvo C70", ucc: "076"},
        {name: "Volvo V70", ucc: "080"},
        {name: "Volvo S80", ucc: "086"},
        {name: "Volvo XC60", ucc: "206"},
        {name: "Volvo XC70", ucc: "216"},
        {name: "Volvo XC90", ucc: "226"},
        {name: "Honda Fit", ucc: "006"},
        {name: "Honda Fit EV", ucc: "007"},
        {name: "Honda Insight Hybrid", ucc: "016"},
        {name: "Honda Civic", ucc: "026"},
        {name: "Honda Civic Hybrid", ucc: "027"},
        {name: "Honda CR-Z", ucc: "036"},
        {name: "Honda Accord", ucc: "046"},
        {name: "Honda Accord Crosstour", ucc: "051"},
        {name: "Honda Element", ucc: "206"},
        {name: "Honda CR-V", ucc: "216"},
        {name: "Honda Pilot", ucc: "226"},
        {name: "Honda Ridgeline", ucc: "406"},
        {name: "Honda Odyssey", ucc: "506"},
        {name: "Acura ILX", ucc: "006"},
        {name: "Acura ILX Hybrid", ucc: "007"},
        {name: "Acura TSX", ucc: "016"},
        {name: "Acura TL", ucc: "026"},
        {name: "Acura TLX", ucc: "027"},
        {name: "Acura RL", ucc: "036"},
        {name: "Acura RLX", ucc: "037"},
        {name: "Acura ZDX", ucc: "206"},
        {name: "Acura RDX", ucc: "216"},
        {name: "Acura MDX", ucc: "226"},
        {name: "Suzuki SX4", ucc: "006"},
        {name: "Suzuki Kizashi", ucc: "016"},
        {name: "Suzuki Grand Vitara", ucc: "206"},
        {name: "Suzuki Equator", ucc: "406"},
        {name: "Hyundai Accent", ucc: "006"},
        {name: "Hyundai Elantra", ucc: "016"},
        {name: "Hyundai Veloster", ucc: "026"},
        {name: "Hyundai Sonata", ucc: "036"},
        {name: "Hyundai Sonata Hybrid", ucc: "037"},
        {name: "Hyundai Azera", ucc: "041"},
        {name: "Hyundai Equus", ucc: "046"},
        {name: "Hyundai Genesis", ucc: "056"},
        {name: "Hyundai Tucson", ucc: "206"},
        {name: "Hyundai Santa Fe Sport", ucc: "216"},
        {name: "Hyundai Santa Fe", ucc: "226"},
        {name: "Hyundai Veracruz", ucc: "236"},
        {name: "Kia Rio", ucc: "006"},
        {name: "Kia Rio 5", ucc: "011"},
        {name: "Kia Forte", ucc: "016"},
        {name: "Kia Soul", ucc: "026"},
        {name: "Kia Optima", ucc: "036"},
        {name: "Kia Optima (Hybrid)", ucc: "037"},
        {name: "Kia Cadenza", ucc: "046"},
        {name: "Kia K900", ucc: "047"},
        {name: "Kia Spectra", ucc: "056"},
        {name: "Kia Sportage", ucc: "206"},
        {name: "Kia Sorento", ucc: "216"},
        {name: "Kia Sedona", ucc: "506"},
        {name: "Mazda Mazda2", ucc: "006"},
        {name: "Mazda Mazda3", ucc: "016"},
        {name: "Mazda Mazda5", ucc: "021"},
        {name: "Mazda Miata MX-5", ucc: "026"},
        {name: "Mazda Mazda6", ucc: "036"},
        {name: "Mazda CX-5", ucc: "206"},
        {name: "Mazda CX-7", ucc: "216"},
        {name: "Mazda CX-9", ucc: "226"},
        {name: "Mitsubishi I-MiEV", ucc: "006"},
        {name: "Mitsubishi Mirage", ucc: "007"},
        {name: "Mitsubishi Lancer", ucc: "016"},
        {name: "Mitsubishi Eclipse", ucc: "026"},
        {name: "Mitsubishi Galant", ucc: "036"},
        {name: "Mitsubishi Outlander Sport", ucc: "206"},
        {name: "Mitsubishi Outlander", ucc: "216"},
        {name: "Nissan Versa", ucc: "006"},
        {name: "Nissan Note/Versa Note", ucc: "011"},
        {name: "Nissan Sentra", ucc: "016"},
        {name: "Nissan Juke", ucc: "023"},
        {name: "Nissan Leaf", ucc: "026"},
        {name: "Nissan Cube", ucc: "036"},
        {name: "Nissan Z", ucc: "046"},
        {name: "Nissan GT-R", ucc: "051"},
        {name: "Nissan Altima", ucc: "056"},
        {name: "Nissan Altima Hybrid", ucc: "057"},
        {name: "Nissan Maxima", ucc: "066"},
        {name: "Nissan Rogue", ucc: "216"},
        {name: "Nissan Rogue Select", ucc: "217"},
        {name: "Nissan Xterra", ucc: "226"},
        {name: "Nissan Murano", ucc: "236"},
        {name: "Nissan Murano Cross Cabriolet", ucc: "237"},
        {name: "Nissan Pathfinder", ucc: "246"},
        {name: "Nissan Armada", ucc: "256"},
        {name: "Nissan Frontier", ucc: "406"},
        {name: "Nissan Titan", ucc: "416"},
        {name: "Nissan Quest", ucc: "506"},
        {name: "Nissan NVP Passenger", ucc: "516"},
        {name: "Nissan NV 200", ucc: "526"},
        {name: "Nissan NV Cargo", ucc: "536"},
        {name: "Infiniti G", ucc: "006"},
        {name: "Infiniti M", ucc: "016"},
        {name: "Infiniti M Hybrid", ucc: "017"},
        {name: "Infiniti Q", ucc: "026"},
        {name: "Infiniti EX", ucc: "206"},
        {name: "Infiniti FX", ucc: "216"},
        {name: "Infiniti JX", ucc: "226"},
        {name: "Infiniti QX", ucc: "236"},
        {name: "Subaru Impreza", ucc: "006"},
        {name: "Subaru Impreza Outback Sport", ucc: "011"},
        {name: "Subaru Impreza WRX", ucc: "016"},
        {name: "Subaru WRX", ucc: "017"},
        {name: "Subaru WRX STI", ucc: "018"},
        {name: "Subaru BRZ", ucc: "026"},
        {name: "Subaru Legacy", ucc: "036"},
        {name: "Subaru Forester", ucc: "206"},
        {name: "Subaru XV Crosstrek", ucc: "216"},
        {name: "Subaru Outback", ucc: "226"},
        {name: "Subaru Tribeca", ucc: "236"},
        {name: "Scion iQ", ucc: "006"},
        {name: "Scion tC", ucc: "016"},
        {name: "Scion FR-S", ucc: "021"},
        {name: "Scion xB", ucc: "026"},
        {name: "Scion xD", ucc: "036"},
        {name: "Toyota Yaris", ucc: "006"},
        {name: "Toyota Prius", ucc: "016"},
        {name: "Toyota Prius c", ucc: "017"},
        {name: "Toyota Prius Plug-in", ucc: "018"},
        {name: "Toyota Prius v", ucc: "019"},
        {name: "Toyota Corolla", ucc: "026"},
        {name: "Toyota Matrix", ucc: "036"},
        {name: "Toyota Camry", ucc: "046"},
        {name: "Toyota Camry Hybrid", ucc: "047"},
        {name: "Toyota Avalon", ucc: "056"},
        {name: "Toyota Avalon Hybrid", ucc: "057"},
        {name: "Toyota FJ Cruiser", ucc: "206"},
        {name: "Toyota RAV4", ucc: "216"},
        {name: "Toyota RAV4 EV", ucc: "217"},
        {name: "Toyota Venza", ucc: "226"},
        {name: "Toyota Highlander", ucc: "236"},
        {name: "Toyota Highlander Hybrid", ucc: "237"},
        {name: "Toyota 4Runner", ucc: "246"},
        {name: "Toyota Sequoia", ucc: "256"},
        {name: "Toyota Land Cruiser", ucc: "266"},
        {name: "Toyota Tacoma", ucc: "406"},
        {name: "Toyota Tundra", ucc: "416"},
        {name: "Toyota Sienna", ucc: "506"},
        {name: "Lexus CT 200h", ucc: "006"},
        {name: "Lexus IS", ucc: "016"},
        {name: "Lexus HS Hybrid", ucc: "026"},
        {name: "Lexus ES", ucc: "036"},
        {name: "Lexus ES Hybrid", ucc: "037"},
        {name: "Lexus GS", ucc: "046"},
        {name: "Lexus GS Hybrid", ucc: "047"},
        {name: "Lexus LS", ucc: "056"},
        {name: "Lexus LS Hybrid", ucc: "057"},
        {name: "Lexus RC", ucc: "066"},
        {name: "Lexus RX", ucc: "206"},
        {name: "Lexus RX Hybrid", ucc: "207"},
        {name: "Lexus GX", ucc: "216"},
        {name: "Lexus LX", ucc: "226"},
        {name: "Lexus NX", ucc: "236"},
        {name: "Aston Martin DB9", ucc: "006"},
        {name: "Aston Martin Rapide", ucc: "016"},
        {name: "Aston Martin Vanquish", ucc: "026"},
        {name: "Aston Martin Vantage", ucc: "036"},
        {name: "McLaren MP4-12C", ucc: "006"},
        {name: "McLaren 650S", ucc: "007"},
        {name: "Bentley Flying Spur", ucc: "006"},
        {name: "Bentley Continental", ucc: "016"},
        {name: "Bentley Musanne", ucc: "026"},
        {name: "Lamborghini Aventador", ucc: "006"},
        {name: "Lamborghini Gallardo", ucc: "016"},
        {name: "Lamborghini Huracan", ucc: "026"},
        {name: "Lotus Evora", ucc: "006"},
        {name: "Maserati Quattroporte", ucc: "006"},
        {name: "Maserati Ghible", ucc: "016"},
        {name: "Maserati Granturismo", ucc: "026"},
        {name: "Rolls-Royce Ghost", ucc: "006"},
        {name: "Rolls-Royce Phanom Drophead", ucc: "016"},
        {name: "Rolls-Royce Phanom", ucc: "026"},
        {name: "Rolls-Royce Wraith", ucc: "036"},
        {name: "Ferrari 458 Italia", ucc: "006"},
        {name: "Ferrari 458 Speciale", ucc: "007"},
        {name: "Ferrari California", ucc: "016"},
        {name: "Ferrari FF", ucc: "026"},
        {name: "Ferrari F12 Berlinetta", ucc: "036"}
    ]

    this.getModels = function () {
        return models;
    };

    this.getModel = function (ucc) {
        var found = models.filter(function (m) {
            return m.ucc = ucc;
        });
        if (found.length < 0)
            throw new Error("now model found for ucc: " + ucc);

        return found[0];
    }
}

angular.module("app")
.service("models", models);