function models() {
    var models = [
        {name: "Chrysler PT Criuser", segment:"Near Luxury Car", ucc: "002"},
        {name: "Chrysler 200", segment:"Near Luxury Car", ucc: "006"},
        {name: "Chrysler 300", segment:"Near Luxury Car", ucc: "016"},
        {name: "Chrysler 300C", segment:"Near Luxury Car", ucc: "017"},
        {name: "Chrysler Sebring", segment:"Near Luxury Car", ucc: "026"},
        {name: "Chrysler Town & Country", segment:"Near Luxury Car", ucc: "506"},
        {name: "Dodge Dart", segment:"Near Luxury Car", ucc: "006"},
        {name: "Dodge Caliber", segment:"Near Luxury Car", ucc: "016"},
        {name: "Dodge Challenger", segment:"Near Luxury Car", ucc: "026"},
        {name: "Dodge Avenger", segment:"Near Luxury Car", ucc: "036"},
        {name: "Dodge Charger", segment:"Near Luxury Car", ucc: "046"},
        {name: "Dodge Viper", segment:"Near Luxury Car", ucc: "056"},
        {name: "Dodge Nitro", segment:"Near Luxury Car", ucc: "206"},
        {name: "Dodge Journey", segment:"Near Luxury Car", ucc: "216"},
        {name: "Dodge Durango", segment:"Near Luxury Car", ucc: "226"},
        {name: "Dodge Grand Caravan", segment:"Near Luxury Car", ucc: "506"},
        {name: "Ram Dakota", segment:"Near Luxury Car", ucc: "406"},
        {name: "Ram 1500", segment:"Near Luxury Car", ucc: "411"},
        {name: "Ram 2500/3500", segment:"Near Luxury Car", ucc: "416"},
        {name: "Ram 3500 Cab Chassis", segment:"Near Luxury Car", ucc: "417"},
        {name: "Ram 4500 Cab Chassis", segment:"Near Luxury Car", ucc: "418"},
        {name: "Ram 5500 Cab Chassis", segment:"Near Luxury Car", ucc: "419"},
        {name: "Ram Medium/Heavy Duty Cab Chassis", segment:"Near Luxury Car", ucc: "421"},
        {name: "Ram Promaster 1500", segment:"Near Luxury Car", ucc: "506"},
        {name: "Ram Promaster 2500", segment:"Near Luxury Car", ucc: "516"},
        {name: "Ram Promaster 3500", segment:"Near Luxury Car", ucc: "526"},
        {name: "Ram Promaster Window Van", segment:"Near Luxury Car", ucc: "536"},
        {name: "Ram Cargo Van", segment:"Near Luxury Car", ucc: "550"},
        {name: "Jeep Wrangler 2D", segment:"Near Luxury Car", ucc: "206"},
        {name: "Jeep Wrangler Unlimited 4D", segment:"Near Luxury Car", ucc: "211"},
        {name: "Jeep Compass", segment:"Near Luxury Car", ucc: "221"},
        {name: "Jeep Patriot", segment:"Near Luxury Car", ucc: "231"},
        {name: "Jeep Liberty", segment:"Near Luxury Car", ucc: "241"},
        {name: "Jeep Cherokee", segment:"Near Luxury Car", ucc: "251"},
        {name: "Jeep Grand Cherokee", segment:"Near Luxury Car", ucc: "261"},
        {name: "Fiat 500", segment:"Near Luxury Car", ucc: "006"},
        {name: "Fiat 500L", segment:"Near Luxury Car", ucc: "016"},
        {name: "Ford C-Max Energi", segment:"Near Luxury Car", ucc: "006"},
        {name: "Ford C-Max Hybrid", segment:"Near Luxury Car", ucc: "007"},
        {name: "Ford Fiesta", segment:"Near Luxury Car", ucc: "016"},
        {name: "Ford Focus", segment:"Near Luxury Car", ucc: "026"},
        {name: "Ford Focus Electric", segment:"Near Luxury Car", ucc: "027"},
        {name: "Ford Mustang", segment:"Near Luxury Car", ucc: "036"},
        {name: "Ford Shelby GT500", segment:"Near Luxury Car", ucc: "041"},
        {name: "Ford Fusion", segment:"Near Luxury Car", ucc: "046"},
        {name: "Ford Fusion Hybrid", segment:"Near Luxury Car", ucc: "047"},
        {name: "Ford Fusion Energi Plug-In Hybrid", segment:"Near Luxury Car", ucc: "048"},
        {name: "Ford Taurus", segment:"Near Luxury Car", ucc: "056"},
        {name: "Ford Escape", segment:"Near Luxury Car", ucc: "206"},
        {name: "Ford Escape Hybrid", segment:"Near Luxury Car", ucc: "207"},
        {name: "Ford Edge", segment:"Near Luxury Car", ucc: "216"},
        {name: "Ford Explorer", segment:"Near Luxury Car", ucc: "226"},
        {name: "Ford Flex", segment:"Near Luxury Car", ucc: "236"},
        {name: "Ford Expedition", segment:"Near Luxury Car", ucc: "246"},
        {name: "Ford Expedition EL", segment:"Near Luxury Car", ucc: "256"},
        {name: "Ford Ranger", segment:"Near Luxury Car", ucc: "406"},
        {name: "Ford F-150", segment:"Near Luxury Car", ucc: "416"},
        {name: "Ford F-250/350 SD", segment:"Near Luxury Car", ucc: "426"},
        {name: "Ford Transit Connect Passenger Wagon", segment:"Near Luxury Car", ucc: "506"},
        {name: "Ford Transit Connect Cargo Van", segment:"Near Luxury Car", ucc: "507"},
        {name: "Ford E-Series Passenger Wagon", segment:"Near Luxury Car", ucc: "516"},
        {name: "Ford E-Series Cargo Van", segment:"Near Luxury Car", ucc: "517"},
        {name: "Ford Transit-150", segment:"Near Luxury Car", ucc: "520"},
        {name: "Ford Transit-250", segment:"Near Luxury Car", ucc: "521"},
        {name: "Ford Transit-350", segment:"Near Luxury Car", ucc: "522"},
        {name: "Lincoln MKS", segment:"Near Luxury Car", ucc: "006"},
        {name: "Lincoln MKZ", segment:"Near Luxury Car", ucc: "016"},
        {name: "Lincoln MKZ Hybrid", segment:"Near Luxury Car", ucc: "017"},
        {name: "Lincoln MKX", segment:"Near Luxury Car", ucc: "206"},
        {name: "Lincoln MKC", segment:"Near Luxury Car", ucc: "207"},
        {name: "Lincoln MKT", segment:"Near Luxury Car", ucc: "216"},
        {name: "Lincoln Navigator", segment:"Near Luxury Car", ucc: "226"},
        {name: "Lincoln Navigator L", segment:"Near Luxury Car", ucc: "236"},
        {name: "Chevrolet Spark", segment:"Near Luxury Car", ucc: "006"},
        {name: "Chevrolet Spark EV", segment:"Near Luxury Car", ucc: "007"},
        {name: "Chevrolet Sonic", segment:"Near Luxury Car", ucc: "016"},
        {name: "Chevrolet Cruze", segment:"Near Luxury Car", ucc: "026"},
        {name: "Chevrolet Volt", segment:"Near Luxury Car", ucc: "036"},
        {name: "Chevrolet Camaro", segment:"Near Luxury Car", ucc: "046"},
        {name: "Chevrolet Corvette", segment:"Near Luxury Car", ucc: "056"},
        {name: "Chevrolet Malibu", segment:"Near Luxury Car", ucc: "066"},
        {name: "Chevrolet Impala", segment:"Near Luxury Car", ucc: "076"},
        {name: "Chevrolet SS", segment:"Near Luxury Car", ucc: "077"},
        {name: "Chevrolet HHR", segment:"Near Luxury Car", ucc: "085"},
        {name: "Chevrolet Aveo", segment:"Near Luxury Car", ucc: "086"},
        {name: "Chevrolet Trax", segment:"Near Luxury Car", ucc: "203"},
        {name: "Chevrolet Equinox", segment:"Near Luxury Car", ucc: "206"},
        {name: "Chevrolet Traverse", segment:"Near Luxury Car", ucc: "216"},
        {name: "Chevrolet Tahoe", segment:"Near Luxury Car", ucc: "226"},
        {name: "Chevrolet Tahoe Hybrid", segment:"Near Luxury Car", ucc: "227"},
        {name: "Chevrolet Suburban", segment:"Near Luxury Car", ucc: "236"},
        {name: "Chevrolet Avalanche", segment:"Near Luxury Car", ucc: "246"},
        {name: "Chevrolet Colorado", segment:"Near Luxury Car", ucc: "406"},
        {name: "Chevrolet Silverado 1500", segment:"Near Luxury Car", ucc: "416"},
        {name: "Chevrolet Silverado 1500 Hybrid", segment:"Near Luxury Car", ucc: "417"},
        {name: "Chevrolet Silverado 2500HD/3500", segment:"Near Luxury Car", ucc: "426"},
        {name: "Chevrolet Express Passenger Wagon", segment:"Near Luxury Car", ucc: "506"},
        {name: "Chevrolet Express Cargo Van", segment:"Near Luxury Car", ucc: "507"},
        {name: "Buick Lucerne", segment:"Near Luxury Car", ucc: "005"},
        {name: "Buick Regal", segment:"Near Luxury Car", ucc: "006"},
        {name: "Buick Verano", segment:"Near Luxury Car", ucc: "016"},
        {name: "Buick Lacrosse", segment:"Near Luxury Car", ucc: "026"},
        {name: "Buick Encore", segment:"Near Luxury Car", ucc: "206"},
        {name: "Buick Enclave", segment:"Near Luxury Car", ucc: "216"},
        {name: "Cadillac ATS", segment:"Near Luxury Car", ucc: "006"},
        {name: "Cadillac CTS", segment:"Near Luxury Car", ucc: "016"},
        {name: "Cadillac CTS-V", segment:"Near Luxury Car", ucc: "017"},
        {name: "Cadillac ELR", segment:"Near Luxury Car", ucc: "020"},
        {name: "Cadillac XTS", segment:"Near Luxury Car", ucc: "026"},
        {name: "Cadillac DTS", segment:"Near Luxury Car", ucc: "036"},
        {name: "Cadillac STS", segment:"Near Luxury Car", ucc: "046"},
        {name: "Cadillac SRX", segment:"Near Luxury Car", ucc: "206"},
        {name: "Cadillac Escalade", segment:"Near Luxury Car", ucc: "216"},
        {name: "Cadillac Escalade Hybrid", segment:"Near Luxury Car", ucc: "217"},
        {name: "Cadillac Escalade ESV", segment:"Near Luxury Car", ucc: "221"},
        {name: "Cadillac Escalade EXT", segment:"Near Luxury Car", ucc: "226"},
        {name: "GMC Terrain", segment:"Near Luxury Car", ucc: "206"},
        {name: "GMC Terrain Denali", segment:"Near Luxury Car", ucc: "207"},
        {name: "GMC Acadia", segment:"Near Luxury Car", ucc: "216"},
        {name: "GMC Yukon", segment:"Near Luxury Car", ucc: "226"},
        {name: "GMC Yukon Denali", segment:"Near Luxury Car", ucc: "227"},
        {name: "GMC Yukon XL", segment:"Near Luxury Car", ucc: "236"},
        {name: "GMC Yukon XL Denali", segment:"Near Luxury Car", ucc: "237"},
        {name: "GMC Canyon", segment:"Near Luxury Car", ucc: "406"},
        {name: "GMC Sierra 1500", segment:"Near Luxury Car", ucc: "416"},
        {name: "GMC Sierra 2500 HD/3500", segment:"Near Luxury Car", ucc: "426"},
        {name: "GMC Savana Passenger Wagon", segment:"Near Luxury Car", ucc: "506"},
        {name: "GMC Savana Cargo Van", segment:"Near Luxury Car", ucc: "507"},
        {name: "Tesla Model S", segment:"Near Luxury Car", ucc: "006"},
        {name: "MINI Cooper Hardtop", segment:"Near Luxury Car", ucc: "006"},
        {name: "MINI Cooper Coupe", segment:"Near Luxury Car", ucc: "016"},
        {name: "MINI Cooper Convertible", segment:"Near Luxury Car", ucc: "026"},
        {name: "MINI Cooper Roadster", segment:"Near Luxury Car", ucc: "036"},
        {name: "MINI Cooper Clubman", segment:"Near Luxury Car", ucc: "046"},
        {name: "MINI Cooper Countryman", segment:"Near Luxury Car", ucc: "056"},
        {name: "MINI Cooper Paceman", segment:"Near Luxury Car", ucc: "066"},
        {name: "BMW ActiveE", segment:"Near Luxury Car", ucc: "003"},
        {name: "BMW Z4", segment:"Near Luxury Car", ucc: "006"},
        {name: "BMW 1 Series", segment:"Near Luxury Car", ucc: "016"},
        {name: "BMW i3", segment:"Near Luxury Car", ucc: "026"},
        {name: "BMW 3 Series", segment:"Near Luxury Car", ucc: "036"},
        {name: "BMW Activehybrid 3", segment:"Near Luxury Car", ucc: "037"},
        {name: "BMW 2 Series", segment:"Near Luxury Car", ucc: "040"},
        {name: "BMW 4 Series", segment:"Near Luxury Car", ucc: "046"},
        {name: "BMW 5 Series", segment:"Near Luxury Car", ucc: "056"},
        {name: "BMW Activehybrid 5", segment:"Near Luxury Car", ucc: "057"},
        {name: "BMW 6 Series", segment:"Near Luxury Car", ucc: "066"},
        {name: "BMW 7 Series", segment:"Near Luxury Car", ucc: "076"},
        {name: "BMW 7 Series Activehybrid", segment:"Near Luxury Car", ucc: "077"},
        {name: "BMW Alpina B7", segment:"Near Luxury Car", ucc: "086"},
        {name: "BMW i8", segment:"Near Luxury Car", ucc: "090"},
        {name: "BMW X1", segment:"Near Luxury Car", ucc: "211"},
        {name: "BMW X3", segment:"Near Luxury Car", ucc: "231"},
        {name: "BMW X4", segment:"Near Luxury Car", ucc: "241"},
        {name: "BMW X5", segment:"Near Luxury Car", ucc: "251"},
        {name: "BMW X6", segment:"Near Luxury Car", ucc: "261"},
        {name: "BMW X6 ActiveHybrid", segment:"Near Luxury Car", ucc: "262"},
        {name: "Mercedes CLA-Class", segment:"Near Luxury Car", ucc: "001"},
        {name: "Mercedes B-Class", segment:"Near Luxury Car", ucc: "002"},
        {name: "Mercedes C-Class", segment:"Near Luxury Car", ucc: "006"},
        {name: "Mercedes CL-Class", segment:"Near Luxury Car", ucc: "011"},
        {name: "Mercedes CLS-Class", segment:"Near Luxury Car", ucc: "016"},
        {name: "Mercedes E-Class", segment:"Near Luxury Car", ucc: "021"},
        {name: "Mercedes E-Class Hybrid", segment:"Near Luxury Car", ucc: "022"},
        {name: "Mercedes S-Class", segment:"Near Luxury Car", ucc: "031"},
        {name: "Mercedes S-Class Hybrid", segment:"Near Luxury Car", ucc: "032"},
        {name: "Mercedes SLK-Class", segment:"Near Luxury Car", ucc: "036"},
        {name: "Mercedes SL-Class", segment:"Near Luxury Car", ucc: "041"},
        {name: "Mercedes SLS AMG", segment:"Near Luxury Car", ucc: "046"},
        {name: "Mercedes GLK-Class", segment:"Near Luxury Car", ucc: "206"},
        {name: "Mercedes R-Class", segment:"Near Luxury Car", ucc: "216"},
        {name: "Mercedes ML-Class", segment:"Near Luxury Car", ucc: "226"},
        {name: "Mercedes ML-Class Hybrid", segment:"Near Luxury Car", ucc: "227"},
        {name: "Mercedes GLA-Class", segment:"Near Luxury Car", ucc: "228"},
        {name: "Mercedes GL-Class", segment:"Near Luxury Car", ucc: "236"},
        {name: "Mercedes G-Class", segment:"Near Luxury Car", ucc: "246"},
        {name: "Smart fortwo", segment:"Near Luxury Car", ucc: "006"},
        {name: "Jaguar F-Type", segment:"Near Luxury Car", ucc: "006"},
        {name: "Jaguar XK", segment:"Near Luxury Car", ucc: "016"},
        {name: "Jaguar XF", segment:"Near Luxury Car", ucc: "026"},
        {name: "Jaguar XJ", segment:"Near Luxury Car", ucc: "036"},
        {name: "Jaguar XJL", segment:"Near Luxury Car", ucc: "046"},
        {name: "Land Rover LR2", segment:"Near Luxury Car", ucc: "206"},
        {name: "Land Rover LR4", segment:"Near Luxury Car", ucc: "216"},
        {name: "Land Rover Range Rover Evoque", segment:"Near Luxury Car", ucc: "226"},
        {name: "Land Rover Range Rover Sport", segment:"Near Luxury Car", ucc: "236"},
        {name: "Land Rover Range Rover", segment:"Near Luxury Car", ucc: "246"},
        {name: "Porsche Boxster", segment:"Near Luxury Car", ucc: "006"},
        {name: "Porsche 911", segment:"Near Luxury Car", ucc: "016"},
        {name: "Porsche Cayman", segment:"Near Luxury Car", ucc: "026"},
        {name: "Porsche Panamera", segment:"Near Luxury Car", ucc: "036"},
        {name: "Porsche Panamera Hybrid", segment:"Near Luxury Car", ucc: "037"},
        {name: "Porsche Cayenne", segment:"Near Luxury Car", ucc: "216"},
        {name: "Porsche Cayenne Hybrid", segment:"Near Luxury Car", ucc: "217"},
        {name: "Porsche Macan", segment:"Near Luxury Car", ucc: "230"},
        {name: "Volkswagen Beetle", segment:"Near Luxury Car", ucc: "006"},
        {name: "Volkswagen Eos", segment:"Near Luxury Car", ucc: "016"},
        {name: "Volkswagen Golf", segment:"Near Luxury Car", ucc: "026"},
        {name: "Volkswagen GTI", segment:"Near Luxury Car", ucc: "036"},
        {name: "Volkswagen Jetta", segment:"Near Luxury Car", ucc: "046"},
        {name: "Volkswagen Jetta Hybrid", segment:"Near Luxury Car", ucc: "047"},
        {name: "Volkswagen CC", segment:"Near Luxury Car", ucc: "056"},
        {name: "Volkswagen Passat", segment:"Near Luxury Car", ucc: "066"},
        {name: "Volkswagen Tiguan", segment:"Near Luxury Car", ucc: "206"},
        {name: "Volkswagen Touareg", segment:"Near Luxury Car", ucc: "216"},
        {name: "Volkswagen Touareg Hybrid", segment:"Near Luxury Car", ucc: "217"},
        {name: "Volkswagen Routan", segment:"Near Luxury Car", ucc: "506"},
        {name: "Audi TT", segment:"Near Luxury Car", ucc: "006"},
        {name: "Audi R8", segment:"Near Luxury Car", ucc: "016"},
        {name: "Audi A3", segment:"Near Luxury Car", ucc: "035"},
        {name: "Audi S3", segment:"Near Luxury Car", ucc: "036"},
        {name: "Audi A4", segment:"Near Luxury Car", ucc: "045"},
        {name: "Audi S4", segment:"Near Luxury Car", ucc: "046"},
        {name: "Audi Allroad", segment:"Near Luxury Car", ucc: "049"},
        {name: "Audi A5", segment:"Near Luxury Car", ucc: "055"},
        {name: "Audi S5", segment:"Near Luxury Car", ucc: "056"},
        {name: "Audi RS 5", segment:"Near Luxury Car", ucc: "059"},
        {name: "Audi A6", segment:"Near Luxury Car", ucc: "065"},
        {name: "Audi S6", segment:"Near Luxury Car", ucc: "066"},
        {name: "Audi A7", segment:"Near Luxury Car", ucc: "075"},
        {name: "Audi S7", segment:"Near Luxury Car", ucc: "076"},
        {name: "Audi RS 7", segment:"Near Luxury Car", ucc: "077"},
        {name: "Audi A8", segment:"Near Luxury Car", ucc: "085"},
        {name: "Audi A8L", segment:"Near Luxury Car", ucc: "086"},
        {name: "Audi S8", segment:"Near Luxury Car", ucc: "087"},
        {name: "Audi Q3", segment:"Near Luxury Car", ucc: "201"},
        {name: "Audi Q5", segment:"Near Luxury Car", ucc: "205"},
        {name: "Audi Q5 Hybrid", segment:"Near Luxury Car", ucc: "206"},
        {name: "Audi Q7", segment:"Near Luxury Car", ucc: "216"},
        {name: "Volvo C30", segment:"Near Luxury Car", ucc: "036"},
        {name: "Volvo S40", segment:"Near Luxury Car", ucc: "046"},
        {name: "Volvo V50", segment:"Near Luxury Car", ucc: "056"},
        {name: "Volvo S60", segment:"Near Luxury Car", ucc: "066"},
        {name: "Volvo V60", segment:"Near Luxury Car", ucc: "067"},
        {name: "Volvo C70", segment:"Near Luxury Car", ucc: "076"},
        {name: "Volvo V70", segment:"Near Luxury Car", ucc: "080"},
        {name: "Volvo S80", segment:"Near Luxury Car", ucc: "086"},
        {name: "Volvo XC60", segment:"Near Luxury Car", ucc: "206"},
        {name: "Volvo XC70", segment:"Near Luxury Car", ucc: "216"},
        {name: "Volvo XC90", segment:"Near Luxury Car", ucc: "226"},
        {name: "Honda Fit", segment:"Near Luxury Car", ucc: "006"},
        {name: "Honda Fit EV", segment:"Near Luxury Car", ucc: "007"},
        {name: "Honda Insight Hybrid", segment:"Near Luxury Car", ucc: "016"},
        {name: "Honda Civic", segment:"Near Luxury Car", ucc: "026"},
        {name: "Honda Civic Hybrid", segment:"Near Luxury Car", ucc: "027"},
        {name: "Honda CR-Z", segment:"Near Luxury Car", ucc: "036"},
        {name: "Honda Accord", segment:"Near Luxury Car", ucc: "046"},
        {name: "Honda Accord Crosstour", segment:"Near Luxury Car", ucc: "051"},
        {name: "Honda Element", segment:"Near Luxury Car", ucc: "206"},
        {name: "Honda CR-V", segment:"Near Luxury Car", ucc: "216"},
        {name: "Honda Pilot", segment:"Near Luxury Car", ucc: "226"},
        {name: "Honda Ridgeline", segment:"Near Luxury Car", ucc: "406"},
        {name: "Honda Odyssey", segment:"Near Luxury Car", ucc: "506"},
        {name: "Acura ILX", segment:"Near Luxury Car", ucc: "006"},
        {name: "Acura ILX Hybrid", segment:"Near Luxury Car", ucc: "007"},
        {name: "Acura TSX", segment:"Near Luxury Car", ucc: "016"},
        {name: "Acura TL", segment:"Near Luxury Car", ucc: "026"},
        {name: "Acura TLX", segment:"Near Luxury Car", ucc: "027"},
        {name: "Acura RL", segment:"Near Luxury Car", ucc: "036"},
        {name: "Acura RLX", segment:"Near Luxury Car", ucc: "037"},
        {name: "Acura ZDX", segment:"Near Luxury Car", ucc: "206"},
        {name: "Acura RDX", segment:"Near Luxury Car", ucc: "216"},
        {name: "Acura MDX", segment:"Near Luxury Car", ucc: "226"},
        {name: "Suzuki SX4", segment:"Near Luxury Car", ucc: "006"},
        {name: "Suzuki Kizashi", segment:"Near Luxury Car", ucc: "016"},
        {name: "Suzuki Grand Vitara", segment:"Near Luxury Car", ucc: "206"},
        {name: "Suzuki Equator", segment:"Near Luxury Car", ucc: "406"},
        {name: "Hyundai Accent", segment:"Near Luxury Car", ucc: "006"},
        {name: "Hyundai Elantra", segment:"Near Luxury Car", ucc: "016"},
        {name: "Hyundai Veloster", segment:"Near Luxury Car", ucc: "026"},
        {name: "Hyundai Sonata", segment:"Near Luxury Car", ucc: "036"},
        {name: "Hyundai Sonata Hybrid", segment:"Near Luxury Car", ucc: "037"},
        {name: "Hyundai Azera", segment:"Near Luxury Car", ucc: "041"},
        {name: "Hyundai Equus", segment:"Near Luxury Car", ucc: "046"},
        {name: "Hyundai Genesis", segment:"Near Luxury Car", ucc: "056"},
        {name: "Hyundai Tucson", segment:"Near Luxury Car", ucc: "206"},
        {name: "Hyundai Santa Fe Sport", segment:"Near Luxury Car", ucc: "216"},
        {name: "Hyundai Santa Fe", segment:"Near Luxury Car", ucc: "226"},
        {name: "Hyundai Veracruz", segment:"Near Luxury Car", ucc: "236"},
        {name: "Kia Rio", segment:"Near Luxury Car", ucc: "006"},
        {name: "Kia Rio 5", segment:"Near Luxury Car", ucc: "011"},
        {name: "Kia Forte", segment:"Near Luxury Car", ucc: "016"},
        {name: "Kia Soul", segment:"Near Luxury Car", ucc: "026"},
        {name: "Kia Optima", segment:"Near Luxury Car", ucc: "036"},
        {name: "Kia Optima (Hybrid)", segment:"Near Luxury Car", ucc: "037"},
        {name: "Kia Cadenza", segment:"Near Luxury Car", ucc: "046"},
        {name: "Kia K900", segment:"Near Luxury Car", ucc: "047"},
        {name: "Kia Spectra", segment:"Near Luxury Car", ucc: "056"},
        {name: "Kia Sportage", segment:"Near Luxury Car", ucc: "206"},
        {name: "Kia Sorento", segment:"Near Luxury Car", ucc: "216"},
        {name: "Kia Sedona", segment:"Near Luxury Car", ucc: "506"},
        {name: "Mazda Mazda2", segment:"Near Luxury Car", ucc: "006"},
        {name: "Mazda Mazda3", segment:"Near Luxury Car", ucc: "016"},
        {name: "Mazda Mazda5", segment:"Near Luxury Car", ucc: "021"},
        {name: "Mazda Miata MX-5", segment:"Near Luxury Car", ucc: "026"},
        {name: "Mazda Mazda6", segment:"Near Luxury Car", ucc: "036"},
        {name: "Mazda CX-5", segment:"Near Luxury Car", ucc: "206"},
        {name: "Mazda CX-7", segment:"Near Luxury Car", ucc: "216"},
        {name: "Mazda CX-9", segment:"Near Luxury Car", ucc: "226"},
        {name: "Mitsubishi I-MiEV", segment:"Near Luxury Car", ucc: "006"},
        {name: "Mitsubishi Mirage", segment:"Near Luxury Car", ucc: "007"},
        {name: "Mitsubishi Lancer", segment:"Near Luxury Car", ucc: "016"},
        {name: "Mitsubishi Eclipse", segment:"Near Luxury Car", ucc: "026"},
        {name: "Mitsubishi Galant", segment:"Near Luxury Car", ucc: "036"},
        {name: "Mitsubishi Outlander Sport", segment:"Near Luxury Car", ucc: "206"},
        {name: "Mitsubishi Outlander", segment:"Near Luxury Car", ucc: "216"},
        {name: "Nissan Versa", segment:"Near Luxury Car", ucc: "006"},
        {name: "Nissan Note/Versa Note", segment:"Near Luxury Car", ucc: "011"},
        {name: "Nissan Sentra", segment:"Near Luxury Car", ucc: "016"},
        {name: "Nissan Juke", segment:"Near Luxury Car", ucc: "023"},
        {name: "Nissan Leaf", segment:"Near Luxury Car", ucc: "026"},
        {name: "Nissan Cube", segment:"Near Luxury Car", ucc: "036"},
        {name: "Nissan Z", segment:"Near Luxury Car", ucc: "046"},
        {name: "Nissan GT-R", segment:"Near Luxury Car", ucc: "051"},
        {name: "Nissan Altima", segment:"Near Luxury Car", ucc: "056"},
        {name: "Nissan Altima Hybrid", segment:"Near Luxury Car", ucc: "057"},
        {name: "Nissan Maxima", segment:"Near Luxury Car", ucc: "066"},
        {name: "Nissan Rogue", segment:"Near Luxury Car", ucc: "216"},
        {name: "Nissan Rogue Select", segment:"Near Luxury Car", ucc: "217"},
        {name: "Nissan Xterra", segment:"Near Luxury Car", ucc: "226"},
        {name: "Nissan Murano", segment:"Near Luxury Car", ucc: "236"},
        {name: "Nissan Murano Cross Cabriolet", segment:"Near Luxury Car", ucc: "237"},
        {name: "Nissan Pathfinder", segment:"Near Luxury Car", ucc: "246"},
        {name: "Nissan Armada", segment:"Near Luxury Car", ucc: "256"},
        {name: "Nissan Frontier", segment:"Near Luxury Car", ucc: "406"},
        {name: "Nissan Titan", segment:"Near Luxury Car", ucc: "416"},
        {name: "Nissan Quest", segment:"Near Luxury Car", ucc: "506"},
        {name: "Nissan NVP Passenger", segment:"Near Luxury Car", ucc: "516"},
        {name: "Nissan NV 200", segment:"Near Luxury Car", ucc: "526"},
        {name: "Nissan NV Cargo", segment:"Near Luxury Car", ucc: "536"},
        {name: "Infiniti G", segment:"Near Luxury Car", ucc: "006"},
        {name: "Infiniti M", segment:"Near Luxury Car", ucc: "016"},
        {name: "Infiniti M Hybrid", segment:"Near Luxury Car", ucc: "017"},
        {name: "Infiniti Q", segment:"Near Luxury Car", ucc: "026"},
        {name: "Infiniti EX", segment:"Near Luxury Car", ucc: "206"},
        {name: "Infiniti FX", segment:"Near Luxury Car", ucc: "216"},
        {name: "Infiniti JX", segment:"Near Luxury Car", ucc: "226"},
        {name: "Infiniti QX", segment:"Near Luxury Car", ucc: "236"},
        {name: "Subaru Impreza", segment:"Near Luxury Car", ucc: "006"},
        {name: "Subaru Impreza Outback Sport", segment:"Near Luxury Car", ucc: "011"},
        {name: "Subaru Impreza WRX", segment:"Near Luxury Car", ucc: "016"},
        {name: "Subaru WRX", segment:"Near Luxury Car", ucc: "017"},
        {name: "Subaru WRX STI", segment:"Near Luxury Car", ucc: "018"},
        {name: "Subaru BRZ", segment:"Near Luxury Car", ucc: "026"},
        {name: "Subaru Legacy", segment:"Near Luxury Car", ucc: "036"},
        {name: "Subaru Forester", segment:"Near Luxury Car", ucc: "206"},
        {name: "Subaru XV Crosstrek", segment:"Near Luxury Car", ucc: "216"},
        {name: "Subaru Outback", segment:"Near Luxury Car", ucc: "226"},
        {name: "Subaru Tribeca", segment:"Near Luxury Car", ucc: "236"},
        {name: "Scion iQ", segment:"Near Luxury Car", ucc: "006"},
        {name: "Scion tC", segment:"Near Luxury Car", ucc: "016"},
        {name: "Scion FR-S", segment:"Near Luxury Car", ucc: "021"},
        {name: "Scion xB", segment:"Near Luxury Car", ucc: "026"},
        {name: "Scion xD", segment:"Near Luxury Car", ucc: "036"},
        {name: "Toyota Yaris", segment:"Near Luxury Car", ucc: "006"},
        {name: "Toyota Prius", segment:"Near Luxury Car", ucc: "016"},
        {name: "Toyota Prius c", segment:"Near Luxury Car", ucc: "017"},
        {name: "Toyota Prius Plug-in", segment:"Near Luxury Car", ucc: "018"},
        {name: "Toyota Prius v", segment:"Near Luxury Car", ucc: "019"},
        {name: "Toyota Corolla", segment:"Near Luxury Car", ucc: "026"},
        {name: "Toyota Matrix", segment:"Near Luxury Car", ucc: "036"},
        {name: "Toyota Camry", segment:"Near Luxury Car", ucc: "046"},
        {name: "Toyota Camry Hybrid", segment:"Near Luxury Car", ucc: "047"},
        {name: "Toyota Avalon", segment:"Near Luxury Car", ucc: "056"},
        {name: "Toyota Avalon Hybrid", segment:"Near Luxury Car", ucc: "057"},
        {name: "Toyota FJ Cruiser", segment:"Near Luxury Car", ucc: "206"},
        {name: "Toyota RAV4", segment:"Near Luxury Car", ucc: "216"},
        {name: "Toyota RAV4 EV", segment:"Near Luxury Car", ucc: "217"},
        {name: "Toyota Venza", segment:"Near Luxury Car", ucc: "226"},
        {name: "Toyota Highlander", segment:"Near Luxury Car", ucc: "236"},
        {name: "Toyota Highlander Hybrid", segment:"Near Luxury Car", ucc: "237"},
        {name: "Toyota 4Runner", segment:"Near Luxury Car", ucc: "246"},
        {name: "Toyota Sequoia", segment:"Near Luxury Car", ucc: "256"},
        {name: "Toyota Land Cruiser", segment:"Near Luxury Car", ucc: "266"},
        {name: "Toyota Tacoma", segment:"Near Luxury Car", ucc: "406"},
        {name: "Toyota Tundra", segment:"Near Luxury Car", ucc: "416"},
        {name: "Toyota Sienna", segment:"Near Luxury Car", ucc: "506"},
        {name: "Lexus CT 200h", segment:"Near Luxury Car", ucc: "006"},
        {name: "Lexus IS", segment:"Near Luxury Car", ucc: "016"},
        {name: "Lexus HS Hybrid", segment:"Near Luxury Car", ucc: "026"},
        {name: "Lexus ES", segment:"Near Luxury Car", ucc: "036"},
        {name: "Lexus ES Hybrid", segment:"Near Luxury Car", ucc: "037"},
        {name: "Lexus GS", segment:"Near Luxury Car", ucc: "046"},
        {name: "Lexus GS Hybrid", segment:"Near Luxury Car", ucc: "047"},
        {name: "Lexus LS", segment:"Near Luxury Car", ucc: "056"},
        {name: "Lexus LS Hybrid", segment:"Near Luxury Car", ucc: "057"},
        {name: "Lexus RC", segment:"Near Luxury Car", ucc: "066"},
        {name: "Lexus RX", segment:"Near Luxury Car", ucc: "206"},
        {name: "Lexus RX Hybrid", segment:"Near Luxury Car", ucc: "207"},
        {name: "Lexus GX", segment:"Near Luxury Car", ucc: "216"},
        {name: "Lexus LX", segment:"Near Luxury Car", ucc: "226"},
        {name: "Lexus NX", segment:"Near Luxury Car", ucc: "236"},
        {name: "Aston Martin DB9", segment:"Near Luxury Car", ucc: "006"},
        {name: "Aston Martin Rapide", segment:"Near Luxury Car", ucc: "016"},
        {name: "Aston Martin Vanquish", segment:"Near Luxury Car", ucc: "026"},
        {name: "Aston Martin Vantage", segment:"Near Luxury Car", ucc: "036"},
        {name: "McLaren MP4-12C", segment:"Near Luxury Car", ucc: "006"},
        {name: "McLaren 650S", segment:"Near Luxury Car", ucc: "007"},
        {name: "Bentley Flying Spur", segment:"Near Luxury Car", ucc: "006"},
        {name: "Bentley Continental", segment:"Near Luxury Car", ucc: "016"},
        {name: "Bentley Musanne", segment:"Near Luxury Car", ucc: "026"},
        {name: "Lamborghini Aventador", segment:"Near Luxury Car", ucc: "006"},
        {name: "Lamborghini Gallardo", segment:"Near Luxury Car", ucc: "016"},
        {name: "Lamborghini Huracan", segment:"Near Luxury Car", ucc: "026"},
        {name: "Lotus Evora", segment:"Near Luxury Car", ucc: "006"},
        {name: "Maserati Quattroporte", segment:"Near Luxury Car", ucc: "006"},
        {name: "Maserati Ghible", segment:"Near Luxury Car", ucc: "016"},
        {name: "Maserati Granturismo", segment:"Near Luxury Car", ucc: "026"},
        {name: "Rolls-Royce Ghost", segment:"Near Luxury Car", ucc: "006"},
        {name: "Rolls-Royce Phanom Drophead", segment:"Near Luxury Car", ucc: "016"},
        {name: "Rolls-Royce Phanom", segment:"Near Luxury Car", ucc: "026"},
        {name: "Rolls-Royce Wraith", segment:"Near Luxury Car", ucc: "036"},
        {name: "Ferrari 458 Italia", segment:"Near Luxury Car", ucc: "006"},
        {name: "Ferrari 458 Speciale", segment:"Near Luxury Car", ucc: "007"},
        {name: "Ferrari California", segment:"Near Luxury Car", ucc: "016"},
        {name: "Ferrari FF", segment:"Near Luxury Car", ucc: "026"},
        {name: "Ferrari F12 Berlinetta", segment:"Near Luxury Car", ucc: "036"}
    ]

    this.getModels = function () {
        return models;
    };

    this.getModel = function (ucc) {
        var found = models.filter(function (m) {
            return m.ucc == ucc;
        });
        if (found.length < 0)
            throw new Error("now model found for ucc: " + ucc);

        return found[0];
    }
}

angular.module("app")
    .service("models", models);